spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive_finance_db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: expense-tracker-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.vikas.financetracker.dto.kfka"


jwt:
  secret: MySuperSecretKeyForJWTGeneration1234567890
  expirationMs: 3600000  # 1 hour
